name: mianah
region: lon
domains:
  - domain: www.mianah.com
    type: PRIMARY
  - domain: mianah.com
    type: ALIAS
static_sites:
  - name: mianah-web
    git:
      repo_clone_url: https://github.com/mt1991-design/mianah-site.git
      branch: main
    source_dir: /
    index_document: index.html
    catchall_document: mianah-home.html
